apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-build-parser
  labels:
    app: cloud-build-parser
spec:
  selector:
    matchLabels:
      app: cloud-build-parser
  template:
    metadata:
      labels:
        app: cloud-build-parser
    spec:
      containers:
      - name: cloud-build-parser
        image: gcr.io/stanke-sandbox-2021-07/cloud-build-parser
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-build-parser
  labels:
    app: cloud-build-parser
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: cloud-build-parser