apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-handler
  labels:
    app: event-handler
spec:
  selector:
    matchLabels:
      app: event-handler
  template:
    metadata:
      labels:
        app: event-handler
    spec:
      containers:
      - name: event-handler
        image: gcr.io/stanke-sandbox-2021-07/event-handler
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: event-handler
  labels:
    app: event-handler
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: event-handler